"""Unit tests for governance.py (generated by cookiecutter)."""

from __future__ import annotations

from pathlib import Path

import pytest

from {{ cookiecutter.package_name }}.governance import (
    PolicyToolFilter,
    build_evaluator,
    load_policies,
)
from {{ cookiecutter.package_name }}.middleware import SessionContext, ToolInvocationContext


# ---------------------------------------------------------------------------
# load_policies
# ---------------------------------------------------------------------------

def test_load_policies_reads_yaml(tmp_path: Path) -> None:
    policy = tmp_path / "p.yaml"
    policy.write_text(
        "name: t\n"
        "version: '1.0'\n"
        "defaults:\n"
        "  action: ALLOW\n"
        "rules: []\n",
        encoding="utf-8",
    )
    doc = load_policies(policy)
    assert doc.name == "t"


def test_load_policies_missing_file_returns_allow_all(
    tmp_path: Path, caplog: pytest.LogCaptureFixture
) -> None:
    missing = tmp_path / "nope.yaml"
    with caplog.at_level("WARNING"):
        doc = load_policies(missing)
    assert doc.name == "allow-all-fallback"
    assert any("policy_file_missing" in rec.message for rec in caplog.records)


def test_load_policies_malformed_yaml_raises(tmp_path: Path) -> None:
    bad = tmp_path / "bad.yaml"
    bad.write_text("- just\n- a\n- list\n", encoding="utf-8")
    with pytest.raises(ValueError):
        load_policies(bad)


# ---------------------------------------------------------------------------
# PolicyToolFilter
# ---------------------------------------------------------------------------

@pytest.mark.asyncio
async def test_policy_tool_filter_blocks_denied_tool(tmp_path: Path) -> None:
    policy = tmp_path / "p.yaml"
    policy.write_text(
        "name: t\n"
        "version: '1.0'\n"
        "defaults:\n"
        "  action: ALLOW\n"
        "rules:\n"
        "  - name: deny-delete\n"
        "    priority: 100\n"
        "    action: DENY\n"
        "    condition:\n"
        "      field: tool_name\n"
        "      operator: IN\n"
        "      value: [delete_file]\n",
        encoding="utf-8",
    )
    evaluator = build_evaluator(policy)
    filt = PolicyToolFilter(evaluator)

    ctx = ToolInvocationContext(
        tool_name="delete_file",
        arguments={},
        session=SessionContext(user_id="u"),
    )
    await filt.before_tool(ctx)
    assert ctx.approved is False
    assert "Blocked by policy" in ctx.denial_reason


@pytest.mark.asyncio
async def test_policy_tool_filter_allows_non_denied_tool(tmp_path: Path) -> None:
    policy = tmp_path / "p.yaml"
    policy.write_text(
        "name: t\n"
        "version: '1.0'\n"
        "defaults:\n"
        "  action: ALLOW\n"
        "rules: []\n",
        encoding="utf-8",
    )
    evaluator = build_evaluator(policy)
    filt = PolicyToolFilter(evaluator)

    ctx = ToolInvocationContext(
        tool_name="web_search",
        arguments={},
        session=SessionContext(user_id="u"),
    )
    await filt.before_tool(ctx)
    assert ctx.approved is True


{%- if cookiecutter.governance_level in ["standard", "full"] %}


# ---------------------------------------------------------------------------
# Input / output providers (standard+)
# ---------------------------------------------------------------------------

from {{ cookiecutter.package_name }}.governance import (  # noqa: E402
    PolicyInputProvider,
    PolicyOutputProvider,
)


@pytest.mark.asyncio
async def test_policy_input_provider_flags_denied_message(tmp_path: Path) -> None:
    policy = tmp_path / "p.yaml"
    policy.write_text(
        "name: t\n"
        "version: '1.0'\n"
        "defaults:\n"
        "  action: ALLOW\n"
        "rules:\n"
        "  - name: deny-secrets\n"
        "    priority: 100\n"
        "    action: DENY\n"
        "    condition:\n"
        "      field: stage\n"
        "      operator: EQ\n"
        "      value: input\n",
        encoding="utf-8",
    )
    evaluator = build_evaluator(policy)
    provider = PolicyInputProvider(evaluator)
    ctx = SessionContext(
        user_id="u",
        messages=[{"role": "user", "content": "anything"}],
    )
    await provider.before_run(ctx)
    assert ctx.state.get("policy_block", {}).get("stage") == "input"


@pytest.mark.asyncio
async def test_policy_output_provider_flags_denied_response(tmp_path: Path) -> None:
    policy = tmp_path / "p.yaml"
    policy.write_text(
        "name: t\n"
        "version: '1.0'\n"
        "defaults:\n"
        "  action: ALLOW\n"
        "rules:\n"
        "  - name: deny-output\n"
        "    priority: 100\n"
        "    action: DENY\n"
        "    condition:\n"
        "      field: stage\n"
        "      operator: EQ\n"
        "      value: output\n",
        encoding="utf-8",
    )
    evaluator = build_evaluator(policy)
    provider = PolicyOutputProvider(evaluator)
    ctx = SessionContext(user_id="u")
    await provider.after_run(ctx, "some response")
    assert ctx.state.get("policy_block", {}).get("stage") == "output"
{%- endif %}


{%- if cookiecutter.governance_level == "full" %}


# ---------------------------------------------------------------------------
# Full tier — audit hook (Task 14)
# ---------------------------------------------------------------------------

@pytest.mark.asyncio
async def test_full_tier_audit_emits_to_agt_compliance(monkeypatch: pytest.MonkeyPatch) -> None:
    """``audit_log_fn`` must forward tool events to AGT's compliance logger."""
    from {{ cookiecutter.package_name }}.utils import logging as log_mod

    emitted: list[dict] = []

    class FakeCompliance:
        def log_event(self, event: dict) -> None:
            emitted.append(event)

    monkeypatch.setattr(log_mod, "_agt_compliance_logger", FakeCompliance())
    await log_mod.audit_log_fn({"event": "tool_call_start", "tool": "x"})
    assert emitted and emitted[0]["event"] == "tool_call_start"
{%- endif %}
